#!/usr/bin/env python3


import os
import argparse


readme_template = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                               'cargo-README-template.md')


def gen_readme(version, feature):
    with open(readme_template, 'r') as f:
        template = f.read()
    new_readme = (template.replace('{{ newestcrate }}', version)
                          .replace('{{ newestfeature }}', feature))
    with open('README.md', 'w') as f:
        f.write(new_readme)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='generate i3ipc readme')
    parser.add_argument('version', help='the crate version x.y.z')
    parser.add_argument('feature', help='the newest feature version i3-x-y')
    args = parser.parse_args()
    gen_readme(args.version, args.feature)
